In [1]:
!wget --no-check-certificate https://jmcauley.ucsd.edu/data/amazon_v2/metaFiles2/meta_Books.json.gz
!gzip -d meta_Books.json.gz

--2023-04-17 08:26:12--  https://jmcauley.ucsd.edu/data/amazon_v2/metaFiles2/meta_Books.json.gz
Resolving jmcauley.ucsd.edu (jmcauley.ucsd.edu)... 137.110.160.73
Connecting to jmcauley.ucsd.edu (jmcauley.ucsd.edu)|137.110.160.73|:443... connected.
WARNING: cannot verify jmcauley.ucsd.edu's certificate, issued by ‘CN=InCommon RSA Server CA,OU=InCommon,O=Internet2,L=Ann Arbor,ST=MI,C=US’:
  Unable to locally verify the issuer's authority.
HTTP request sent, awaiting response... 200 OK
Length: 1219104464 (1.1G) [application/x-gzip]
Saving to: ‘meta_Books.json.gz’

meta_Books.json.gz  100%[===================>]   1.13G  21.7MB/s    in 55s

2023-04-17 08:27:08 (21.1 MB/s) - ‘meta_Books.json.gz’ saved [1219104464/1219104464]

In [2]:
import numpy as np
import pandas as pd

In [3]:
chunksize = 500000
children = pd.DataFrame()
for chunk in pd.read_json("meta_Books.json", lines=True, chunksize=chunksize):
    children = pd.concat([children, chunk], ignore_index=True)
# children = pd.read_json("meta_Books.json", lines=True, chunksize=chunksize)

In [4]:
children.tail()

,category,tech1,description,fit,title,also_buy,tech2,brand,feature,rank,also_view,main_cat,similar_item,date,price,asin,imageURL,imageURLHighRes,details
2934944,"[Books, Mystery, Thriller & Suspense, Thriller...",,[],,Made Men: A Thriller (Law of Retaliation Book ...,[B01CRJ3J1I],,Visit Amazon's Bradley Ernst Page,[],"1,436,585 Paid in Kindle Store (",[],Buy a Kindle,,,,B01HJBPTUI,[],[],"{'File Size:': '1963 KB', 'Print Length:': '27..."
2934945,"[Books, Literature & Fiction, Erotica]",,[],,Raptor&#39;s Desire (A Planet Desire novelette...,"[B01CWFQJKU, B01G7W20HA, B01CXJDC0U, B01H3XUPV...",,Visit Amazon's Delilah Devlin Page,[],"1,060,621 Paid in Kindle Store (",[],Buy a Kindle,,,,B01HJC63ZM,[],[],"{'File Size:': '1903 KB', 'Print Length:': '50..."
2934946,[],,[],,"LG K4 Case,LG Optimus Zone 3 Case,LG Spree Cas...",[],,,[],[],[],Books,,,,B01HJEB422,[],[],{'Publisher:': 'Veggzy is a young and dynamic ...
2934947,"[Books, Religion & Spirituality, New Age & Spi...",,[],,Magickal Incantations,"[B06XP26WK7, B0797Y6JH6, B01M72TG0D, B00JCFEMB...",,SilvrMyst,[],"645,067 Paid in Kindle Store (",[],Buy a Kindle,,,,B01HJDS76Y,[],[],"{'File Size:': '164 KB', 'Print Length:': '10 ..."
2934948,[],,[],,White Away EURO 2016 Match Football Soccer Adu...,[],,,[],"5,339,602 in Books (",[],Books,,,,B01HJFHYMA,[],[],{'ASIN:': 'B01HJFHYMA'}

In [6]:
columns_remain = ['category', 'description', 'title', 'also_buy', 'also_view', 'price', 'asin']
remain = children[columns_remain]

In [7]:
remain['class'] = remain['category'].apply(lambda x : False if len(x) <= 1 else True)
remain = remain.drop(remain[remain['class'] == False].index)
remain['class'] = remain['category'].apply(lambda x : False if x[1] != 'History' else True) #TBA
remain = remain.drop(remain[remain['class'] == False].index)
remain['class'] = remain['category'].apply(lambda x : False if len(x) <= 2 else True)
remain = remain.drop(remain[remain['class'] == False].index)

/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [8]:
remain['category'] = remain['category'].apply(lambda x : x[2])

In [9]:
remain

,category,description,title,also_buy,also_view,price,asin,class
220,Military,"[In 1941, the United States inaugurated a new ...","Seek, Strike and Destroy: U.S. Army Tank Destr...",[],[B0030IMF0W],$47.83,0001953451,True
231,World,[The true story of the remarkable John Rae - A...,"Fatal passage: The untold story of John Rae, t...","[0816041245, 0763650803, 1567318630]","[1771641738, 1472948696, 0316486094, 039324938...",$99.20,0002000547,True
255,Military,[great shape],The Battle of the St. Lawrence; The Second Wor...,[],[],$10.49,0002006642,True
266,Military,[],Victory at Falaise: The Soldier's Story,[],[],$11.17,0002000172,True
271,Americas,"[, James Raffan is one of our foremost authori...",Emperor Of The North,"[0393340023, 0670829692, 0670803790]",[],$5.89,0002007835,True
...,...,...,...,...,...,...,...,...
2934076,World,[],Elektra; A Guide to the Opera with Musical Exa...,[],[],$11.95,B01H69PYRG,True
2934121,Americas,[La obra que tiene en sus manos el lector aspi...,Historia de Tijuana: Semblanza General,[],[],$38.84,B01H7I9R1A,True
2934595,Americas,[],The Stonewall Brigade,"[B07MSMYVN4, B01A4B1T18]","[B00KQ2Z22I, B078J8QBX6, B01M3WCOPE, B079Y3KKM...",,B01HE91YPE,True
2934649,World,[],The Greatest Deception eBook,[],[],,B01HF7RNP0,True
2934804,World,[],A Heritage of Faith,"[B07FB9QVR1, B00EVA5NG6]","[B07GBHCN7W, B07FB9QVR1, B07HBC6DK3]",,B01HHD0A7K,True

In [10]:
remain = remain.reset_index(drop=True)
# remain['class'] = remain['description'].apply(lambda x : False if len(x) == 0 else True)
# remain = remain.drop(remain[remain['class'] == False].index)
remain['class'] = remain['description'].apply(lambda x: True if len([i for i in x if i]) > 0 else False)
remain = remain.drop(remain[remain['class'] == False].index)

remain['class'] = remain['title'].apply(lambda x: True if len([i for i in x if i]) > 0 else False)
remain = remain.drop(remain[remain['class'] == False].index)

In [11]:
remain = remain.reset_index(drop=True)
remain

,category,description,title,also_buy,also_view,price,asin,class
0,Military,"[In 1941, the United States inaugurated a new ...","Seek, Strike and Destroy: U.S. Army Tank Destr...",[],[B0030IMF0W],$47.83,0001953451,True
1,World,[The true story of the remarkable John Rae - A...,"Fatal passage: The untold story of John Rae, t...","[0816041245, 0763650803, 1567318630]","[1771641738, 1472948696, 0316486094, 039324938...",$99.20,0002000547,True
2,Military,[great shape],The Battle of the St. Lawrence; The Second Wor...,[],[],$10.49,0002006642,True
3,Americas,"[, James Raffan is one of our foremost authori...",Emperor Of The North,"[0393340023, 0670829692, 0670803790]",[],$5.89,0002007835,True
4,Americas,"[, Charlotte Gray is one of Canada&#8217;s bes...",Gold Diggers,"[0786713178, 0804009279, 0385658443, 1977052436]","[0307461734, 0380430266]",$22.97,0002008572,True
...,...,...,...,...,...,...,...,...
85695,Americas,[... the success of this raid proved the real ...,A Far-Flung Gamble: Havana 1762,"[1849083746, 1849082456, 1472826833, 147282496...",[1849083746],$10.99,B01FKTHDDW,True
85696,Americas,[This second edition contains more than 1200 a...,The Supreme Court of the United States (The Ox...,[],[],$17.91,B01FKWMRDA,True
85697,World,[Newsweek Magazine 2016 Special Edition Featur...,Hitler NEWSWEEK SPECIAL EDITION 2016 Can his e...,[B01MZIAU8S],[],,B01GC8XP4G,True
85698,Military,[Created by the crew of USS Rehoboth (AGS-50) ...,USS Rehoboth (AGS-50) Navy Cruise Book 1969 Vi...,[],[],,B01GM8UGCU,True
85699,Americas,[La obra que tiene en sus manos el lector aspi...,Historia de Tijuana: Semblanza General,[],[],$38.84,B01H7I9R1A,True

In [12]:
def extract_text(lst):
    lst = [s for s in lst if s != '']
    return ''.join(lst)


remain['cleaned_desc'] = remain['description'].apply(extract_text)
remain

,category,description,title,also_buy,also_view,price,asin,class,cleaned_desc
0,Military,"[In 1941, the United States inaugurated a new ...","Seek, Strike and Destroy: U.S. Army Tank Destr...",[],[B0030IMF0W],$47.83,0001953451,True,"In 1941, the United States inaugurated a new m..."
1,World,[The true story of the remarkable John Rae - A...,"Fatal passage: The untold story of John Rae, t...","[0816041245, 0763650803, 1567318630]","[1771641738, 1472948696, 0316486094, 039324938...",$99.20,0002000547,True,The true story of the remarkable John Rae - Ar...
2,Military,[great shape],The Battle of the St. Lawrence; The Second Wor...,[],[],$10.49,0002006642,True,great shape
3,Americas,"[, James Raffan is one of our foremost authori...",Emperor Of The North,"[0393340023, 0670829692, 0670803790]",[],$5.89,0002007835,True,James Raffan is one of our foremost authoritie...
4,Americas,"[, Charlotte Gray is one of Canada&#8217;s bes...",Gold Diggers,"[0786713178, 0804009279, 0385658443, 1977052436]","[0307461734, 0380430266]",$22.97,0002008572,True,Charlotte Gray is one of Canada&#8217;s best-k...
...,...,...,...,...,...,...,...,...,...
85695,Americas,[... the success of this raid proved the real ...,A Far-Flung Gamble: Havana 1762,"[1849083746, 1849082456, 1472826833, 147282496...",[1849083746],$10.99,B01FKTHDDW,True,... the success of this raid proved the real p...
85696,Americas,[This second edition contains more than 1200 a...,The Supreme Court of the United States (The Ox...,[],[],$17.91,B01FKWMRDA,True,This second edition contains more than 1200 ar...
85697,World,[Newsweek Magazine 2016 Special Edition Featur...,Hitler NEWSWEEK SPECIAL EDITION 2016 Can his e...,[B01MZIAU8S],[],,B01GC8XP4G,True,Newsweek Magazine 2016 Special Edition Feature...
85698,Military,[Created by the crew of USS Rehoboth (AGS-50) ...,USS Rehoboth (AGS-50) Navy Cruise Book 1969 Vi...,[],[],,B01GM8UGCU,True,Created by the crew of USS Rehoboth (AGS-50) t...
85699,Americas,[La obra que tiene en sus manos el lector aspi...,Historia de Tijuana: Semblanza General,[],[],$38.84,B01H7I9R1A,True,La obra que tiene en sus manos el lector aspir...

In [14]:
def get_value(row):
    return "Description: {0}; Title: {1}".format(row['cleaned_desc'], row['title'])

remain['text'] = remain.apply(get_value, axis=1)
remain = remain.drop(['description', 'title', 'class'], axis=1)
remain

,category,also_buy,also_view,price,asin,cleaned_desc,text
0,Military,[],[B0030IMF0W],$47.83,0001953451,"In 1941, the United States inaugurated a new m...","Description: In 1941, the United States inaugu..."
1,World,"[0816041245, 0763650803, 1567318630]","[1771641738, 1472948696, 0316486094, 039324938...",$99.20,0002000547,The true story of the remarkable John Rae - Ar...,Description: The true story of the remarkable ...
2,Military,[],[],$10.49,0002006642,great shape,Description: great shape; Title: The Battle of...
3,Americas,"[0393340023, 0670829692, 0670803790]",[],$5.89,0002007835,James Raffan is one of our foremost authoritie...,Description: James Raffan is one of our foremo...
4,Americas,"[0786713178, 0804009279, 0385658443, 1977052436]","[0307461734, 0380430266]",$22.97,0002008572,Charlotte Gray is one of Canada&#8217;s best-k...,Description: Charlotte Gray is one of Canada&#...
...,...,...,...,...,...,...,...
85695,Americas,"[1849083746, 1849082456, 1472826833, 147282496...",[1849083746],$10.99,B01FKTHDDW,... the success of this raid proved the real p...,Description: ... the success of this raid prov...
85696,Americas,[],[],$17.91,B01FKWMRDA,This second edition contains more than 1200 ar...,Description: This second edition contains more...
85697,World,[B01MZIAU8S],[],,B01GC8XP4G,Newsweek Magazine 2016 Special Edition Feature...,Description: Newsweek Magazine 2016 Special Ed...
85698,Military,[],[],,B01GM8UGCU,Created by the crew of USS Rehoboth (AGS-50) t...,Description: Created by the crew of USS Rehobo...
85699,Americas,[],[],$38.84,B01H7I9R1A,La obra que tiene en sus manos el lector aspir...,Description: La obra que tiene en sus manos el...

In [15]:
import re
def clean(text):
    # 替换HTML标签和空白
    text = re.sub('<[^<]+?>', '', text)  # 去除HTML标签
    text = re.sub('\s+', ' ', text)  # 去除多余空白
    return text
remain['text'] = remain['text'].apply(lambda x : clean(x))
remain

,category,also_buy,also_view,price,asin,cleaned_desc,text
0,Military,[],[B0030IMF0W],$47.83,0001953451,"In 1941, the United States inaugurated a new m...","Description: In 1941, the United States inaugu..."
1,World,"[0816041245, 0763650803, 1567318630]","[1771641738, 1472948696, 0316486094, 039324938...",$99.20,0002000547,The true story of the remarkable John Rae - Ar...,Description: The true story of the remarkable ...
2,Military,[],[],$10.49,0002006642,great shape,Description: great shape; Title: The Battle of...
3,Americas,"[0393340023, 0670829692, 0670803790]",[],$5.89,0002007835,James Raffan is one of our foremost authoritie...,Description: James Raffan is one of our foremo...
4,Americas,"[0786713178, 0804009279, 0385658443, 1977052436]","[0307461734, 0380430266]",$22.97,0002008572,Charlotte Gray is one of Canada&#8217;s best-k...,Description: Charlotte Gray is one of Canada&#...
...,...,...,...,...,...,...,...
85695,Americas,"[1849083746, 1849082456, 1472826833, 147282496...",[1849083746],$10.99,B01FKTHDDW,... the success of this raid proved the real p...,Description: ... the success of this raid prov...
85696,Americas,[],[],$17.91,B01FKWMRDA,This second edition contains more than 1200 ar...,Description: This second edition contains more...
85697,World,[B01MZIAU8S],[],,B01GC8XP4G,Newsweek Magazine 2016 Special Edition Feature...,Description: Newsweek Magazine 2016 Special Ed...
85698,Military,[],[],,B01GM8UGCU,Created by the crew of USS Rehoboth (AGS-50) t...,Description: Created by the crew of USS Rehobo...
85699,Americas,[],[],$38.84,B01H7I9R1A,La obra que tiene en sus manos el lector aspir...,Description: La obra que tiene en sus manos el...

In [16]:
remain.iloc[32110].loc['text']
remain.drop(['cleaned_desc'], axis=1)

,category,also_buy,also_view,price,asin,text
0,Military,[],[B0030IMF0W],$47.83,0001953451,"Description: In 1941, the United States inaugu..."
1,World,"[0816041245, 0763650803, 1567318630]","[1771641738, 1472948696, 0316486094, 039324938...",$99.20,0002000547,Description: The true story of the remarkable ...
2,Military,[],[],$10.49,0002006642,Description: great shape; Title: The Battle of...
3,Americas,"[0393340023, 0670829692, 0670803790]",[],$5.89,0002007835,Description: James Raffan is one of our foremo...
4,Americas,"[0786713178, 0804009279, 0385658443, 1977052436]","[0307461734, 0380430266]",$22.97,0002008572,Description: Charlotte Gray is one of Canada&#...
...,...,...,...,...,...,...
85695,Americas,"[1849083746, 1849082456, 1472826833, 147282496...",[1849083746],$10.99,B01FKTHDDW,Description: ... the success of this raid prov...
85696,Americas,[],[],$17.91,B01FKWMRDA,Description: This second edition contains more...
85697,World,[B01MZIAU8S],[],,B01GC8XP4G,Description: Newsweek Magazine 2016 Special Ed...
85698,Military,[],[],,B01GM8UGCU,Description: Created by the crew of USS Rehobo...
85699,Americas,[],[],$38.84,B01H7I9R1A,Description: La obra que tiene en sus manos el...

In [17]:
remain = remain.reset_index(drop=True)
# remain.reset_index(drop=True)
out = remain[['category','also_buy','also_view', 'price', 'asin', 'text']]

In [18]:
out.to_csv("cleaned.csv", index=None)

## Feature Engineering

In [19]:
remain = pd.read_csv("cleaned.csv")

In [20]:
remain.reset_index()

,index,category,also_buy,also_view,price,asin,text
0,0,Military,[],['B0030IMF0W'],$47.83,0001953451,"Description: In 1941, the United States inaugu..."
1,1,World,"['0816041245', '0763650803', '1567318630']","['1771641738', '1472948696', '0316486094', '03...",$99.20,0002000547,Description: The true story of the remarkable ...
2,2,Military,[],[],$10.49,0002006642,Description: great shape; Title: The Battle of...
3,3,Americas,"['0393340023', '0670829692', '0670803790']",[],$5.89,0002007835,Description: James Raffan is one of our foremo...
4,4,Americas,"['0786713178', '0804009279', '0385658443', '19...","['0307461734', '0380430266']",$22.97,0002008572,Description: Charlotte Gray is one of Canada&#...
...,...,...,...,...,...,...,...
85695,85695,Americas,"['1849083746', '1849082456', '1472826833', '14...",['1849083746'],$10.99,B01FKTHDDW,Description: ... the success of this raid prov...
85696,85696,Americas,[],[],$17.91,B01FKWMRDA,Description: This second edition contains more...
85697,85697,World,['B01MZIAU8S'],[],NaN,B01GC8XP4G,Description: Newsweek Magazine 2016 Special Ed...
85698,85698,Military,[],[],NaN,B01GM8UGCU,Description: Created by the crew of USS Rehobo...
85699,85699,Americas,[],[],$38.84,B01H7I9R1A,Description: La obra que tiene en sus manos el...

In [21]:
remain

,category,also_buy,also_view,price,asin,text
0,Military,[],['B0030IMF0W'],$47.83,0001953451,"Description: In 1941, the United States inaugu..."
1,World,"['0816041245', '0763650803', '1567318630']","['1771641738', '1472948696', '0316486094', '03...",$99.20,0002000547,Description: The true story of the remarkable ...
2,Military,[],[],$10.49,0002006642,Description: great shape; Title: The Battle of...
3,Americas,"['0393340023', '0670829692', '0670803790']",[],$5.89,0002007835,Description: James Raffan is one of our foremo...
4,Americas,"['0786713178', '0804009279', '0385658443', '19...","['0307461734', '0380430266']",$22.97,0002008572,Description: Charlotte Gray is one of Canada&#...
...,...,...,...,...,...,...
85695,Americas,"['1849083746', '1849082456', '1472826833', '14...",['1849083746'],$10.99,B01FKTHDDW,Description: ... the success of this raid prov...
85696,Americas,[],[],$17.91,B01FKWMRDA,Description: This second edition contains more...
85697,World,['B01MZIAU8S'],[],NaN,B01GC8XP4G,Description: Newsweek Magazine 2016 Special Ed...
85698,Military,[],[],NaN,B01GM8UGCU,Description: Created by the crew of USS Rehobo...
85699,Americas,[],[],$38.84,B01H7I9R1A,Description: La obra que tiene en sus manos el...

In [22]:
categories = list(remain['category'].unique())
old_dict = dict(enumerate(categories))
class_to_number = {value: key for key, value in old_dict.items()}

remain['label'] = remain['category'].map(class_to_number)
# remain

In [23]:
remain['asin_id'] = pd.factorize(remain['asin'])[0]
asin_to_id = remain[['asin', 'asin_id']].drop_duplicates().set_index('asin') #去重过的
df_filtered = remain[remain['asin'].isin(asin_to_id.index)]
df_filtered.drop_duplicates(subset = ['asin'], keep='last', inplace=True)

In [24]:
asin_to_id

            asin_id
asin
0001953451        0
0002000547        1
0002006642        2
0002007835        3
0002008572        4
...             ...
B01FKTHDDW    85612
B01FKWMRDA    85613
B01GC8XP4G    85614
B01GM8UGCU    85615
B01H7I9R1A    85616

[85617 rows x 1 columns]

In [26]:
import ast
my_list = ast.literal_eval(df_filtered['also_buy'][2])

[]

In [27]:
df_filtered['also_buy'] = df_filtered['also_buy'].apply(lambda x : ast.literal_eval(x))

In [28]:
df_filtered['also_view'] = df_filtered['also_view'].apply(lambda x : ast.literal_eval(x))

In [31]:
df_filtered['also_buy'] = df_filtered['also_buy'].apply(lambda x: [asin for asin in x if asin in asin_to_id.index])
df_filtered['also_buy'] = df_filtered['also_buy'].apply(lambda x: [asin_to_id.loc[asin, 'asin_id'] for asin in x])
df_filtered['also_view'] = df_filtered['also_view'].apply(lambda x: [asin for asin in x if asin in asin_to_id.index])
df_filtered['also_view'] = df_filtered['also_view'].apply(lambda x: [asin_to_id.loc[asin, 'asin_id'] for asin in x])

In [32]:
df_filtered

,category,also_buy,also_view,price,asin,text,label,asin_id
0,Military,[],[],$47.83,0001953451,"Description: In 1941, the United States inaugu...",0,0
1,World,[36140],"[57821, 11012, 8354, 27988, 10203, 8119, 11013...",$99.20,0002000547,Description: The true story of the remarkable ...,1,1
2,Military,[],[],$10.49,0002006642,Description: great shape; Title: The Battle of...,0,2
3,Americas,[15881],[],$5.89,0002007835,Description: James Raffan is one of our foremo...,2,3
4,Americas,"[30294, 10633]",[],$22.97,0002008572,Description: Charlotte Gray is one of Canada&#...,2,4
...,...,...,...,...,...,...,...,...
85695,Americas,"[75283, 75232, 18377, 74428, 57727, 74640, 577...",[75283],$10.99,B01FKTHDDW,Description: ... the success of this raid prov...,2,85612
85696,Americas,[],[],$17.91,B01FKWMRDA,Description: This second edition contains more...,2,85613
85697,World,[],[],NaN,B01GC8XP4G,Description: Newsweek Magazine 2016 Special Ed...,1,85614
85698,Military,[],[],NaN,B01GM8UGCU,Description: Created by the crew of USS Rehobo...,0,85615
85699,Americas,[],[],$38.84,B01H7I9R1A,Description: La obra que tiene en sus manos el...,2,85616

In [33]:
df_filtered = df_filtered.reset_index()

In [34]:
df_filtered.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 85617 entries, 0 to 85616
Data columns (total 9 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   index      85617 non-null  int64
 1   category   85617 non-null  object
 2   also_buy   85617 non-null  object
 3   also_view  85617 non-null  object
 4   price      61293 non-null  object
 5   asin       85617 non-null  object
 6   text       85617 non-null  object
 7   label      85617 non-null  int64
 8   asin_id    85617 non-null  int64
dtypes: int64(3), object(6)
memory usage: 5.9+ MB

In [35]:
df_filtered.to_csv("cleaned_and_filtered_final.csv", index=None)

## 画图

In [36]:
!pip install dgl

Collecting dgl
  Downloading dgl-1.0.1-cp37-cp37m-manylinux1_x86_64.whl (5.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.4/5.4 MB 38.5 MB/s eta 0:00:0000:0100:01
Requirement already satisfied: numpy>=1.14.0 in /opt/conda/lib/python3.7/site-packages (from dgl) (1.21.6)
Requirement already satisfied: scipy>=1.1.0 in /opt/conda/lib/python3.7/site-packages (from dgl) (1.7.3)
Requirement already satisfied: tqdm in /opt/conda/lib/python3.7/site-packages (from dgl) (4.64.1)
Requirement already satisfied: psutil>=5.8.0 in /opt/conda/lib/python3.7/site-packages (from dgl) (5.9.3)
Requirement already satisfied: networkx>=2.1 in /opt/conda/lib/python3.7/site-packages (from dgl) (2.6.3)
Requirement already satisfied: requests>=2.19.0 in /opt/conda/lib/python3.7/site-packages (from dgl) (2.28.2)
Requirement already satisfied: idna<4,>=2.5 in /opt/conda/lib/python3.7/site-packages (from requests>=2.19.0->dgl) (3.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /opt/conda/lib/python3.7/site-packages (from requests>=2.19.0->dgl) (1.26.14)
Requirement already satisfied: certifi>=2017.4.17 in /opt/conda/lib/python3.7/site-packages (from requests>=2.19.0->dgl) (2022.12.7)
Requirement already satisfied: charset-normalizer<4,>=2 in /opt/conda/lib/python3.7/site-packages (from requests>=2.19.0->dgl) (2.1.1)
Installing collected packages: dgl
Successfully installed dgl-1.0.1
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

In [37]:
new_df = df_filtered
new_df['node_id'] = pd.factorize(new_df['asin_id'])[0]
new_df['merge'] = new_df['also_view'] + new_df['also_buy']
new_df['merge'] = new_df['merge'].apply(lambda x : list(set(x)))
new_df['merge'] = new_df['merge'].apply(lambda x : sorted(x))

In [38]:
adj_list = {}
asin_ids = sorted(new_df['node_id'].unique())
for asin_id in asin_ids:
    adj_list[asin_id] = []
for index, row in new_df.iterrows():
    src_asin_id = row['node_id']
    merge_asins = row['merge']
    for dest_asin in merge_asins:
        adj_list[src_asin_id].append(dest_asin)

In [39]:
pairs = []
adj0 = []
adj1 = []
for src_asin_id, neighbors in adj_list.items():
    for dest_asin_id in neighbors:
        adj0.append(src_asin_id)
        adj1.append(dest_asin_id)

In [53]:
# new_df.to_csv("history.csv", index=None)

In [40]:
# import dgl
# import torch
# adj0 = torch.tensor(adj0)
# adj1 = torch.tensor(adj1)

# # u = torch.tensor([0, 0, 0, 0, 0])
# # v = torch.tensor([1, 2, 3, 4, 5])
# G = dgl.graph((adj0, adj1))
# G.ndata['label'] = torch.tensor(list(new_df['label']))
# dgl.save_graphs("Amazon-Books-History.pt", G) #TBA
# # 从本地加载图数据
# g = dgl.load_graphs("Amazon-Books-History.pt")[0][0] #TBA

DGL backend not selected or invalid.  Assuming PyTorch for now.

Setting the default backend to "pytorch". You can change it in the ~/.dgl/config.json file or export the DGLBACKEND environment variable.  Valid options are: pytorch, mxnet, tensorflow (all lowercase)

DGLError: Expect number of features to match number of nodes (len(u)). Got 85617 and 85613 instead.

In [ ]:
# #! 保存node_id与其对应的文本数据
# Children_text = new_df[['node_id','text']]
# Children_text.to_json('Amazon_Books_History_text.json') #TBA
# text = pd.read_json('Amazon_Books_History_text.json') #TBA
# #! 将node_id 转为索引
# text.set_index(['node_id'], inplace=True)
# text = text['text']
# import csv
# text.to_csv('Amazon_Books_History.txt', sep=' ', index=False,header=False) #TBA
# txt = pd.read_csv('Amazon_Books_History.txt', header=None) #TBA


# # # 节点特征
# # # G.ndata['feat'] = torch.randn(756,32)
# # # G.ndata['label'] = torch.tensor(df_filtered['class'])
# import dgl, torch
# from torch.utils.data import random_split
# torch.manual_seed(0)
# train_dataset, test_idx = random_split(
#     dataset=range(len(text['node_id'])),
#     lengths=[93449, 23362],
#     generator=torch.Generator().manual_seed(0)
# )
# train_idx, val_idx = random_split(
#     dataset=train_dataset,
#     lengths=[58406, 35043],
#     generator=torch.Generator().manual_seed(0)
# )
# torch.from_numpy(np.array(train_idx))
# graph = dgl.load_graphs("Amazon-Books-History.pt")[0][0] #TBA
# labels1 = torch.unsqueeze(graph.ndata['label'], 1)
# device = torch.device("cuda:2")
# labels1 = torch.unsqueeze(labels1, 1)

In [ ]:
# new_df

In [ ]:
new_df = new_df.drop(['asin_id'], axis=1)
# new_df

In [ ]:
new_df.to_csv("final.csv", index=None)